### PR TITLE
Release: v1.0.0 (Log messages description included)

### LINKED ISSUE #110: Release: v1.0.0
### Name the Issue

- [X] I have named this issue using the new version number.
- A description of ReBACH log messages (screen and file) will be included in this release.
### Steps

- [x] Check that the title of this issue reflects the new version number.
- [x] Create a new branch by clicking on `create branch` on the right-hand sidebar (as shown in the [GitHub docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-a-branch-for-an-issue)). Leave all options as default.
- [x] In the new branch, update `version.py` with the new version number and commit.
- [ ] Create a [new PR](../pulls). Ensure the base branch is `main` or `master` and the comparison branch is the new branch. Use the "Release" PR template.

### PR DESCRIPTION
**Pull request by HafeezOJ**
**Description**

This pull request releases ReBACH v1.0.0. Closes #110 

  
**Check**
- [x] Title and description have been updated.
- [x] Verified the correct branch is being merged by checking the text immediately below the PR title.

**Begin a new release**
:warning: Do not publish the release until this PR is merged :warning:
- [x] Go to the [New Release](../releases/new) page
- [x] In the `Choose a tag` dropdown, enter a new tag name corresponding to the new version. E.g., `v1.0.1`. Then click "Create new tag on publish"
- [x] The `Target` should be the main or master branch.
- [x] Click the `Generate release notes` button. Review the notes for accuracy
- [x] Save the release as Draft.

**Update Documentation in the Branch**
- [x] Copy the generated release notes from the previous step to the top of `CHANGELOG.md`
- [x] Update `README.md` (if needed)

**Release**
- [x] Merge this PR
- [ ] Return to [Releases](../releases) and publish the draft release.

### CODE REVIEW

**Comment by HafeezOJ** [comment]
Not yet, I am working on the steps.

**Comment by HafeezOJ** [comment]
I've completed the steps.

**Review by zoidy — APPROVED** [review]
Looks great!

**Comment by HafeezOJ** [comment]
ReBACH v1.0.0 released!

**Pull request merged**
